chore: changes to backend to account for frontend
turnbasedgames/website pull request #41
Opened 2022-09-09 20:23 UTC by yquansah

This change is to account for a breaking change on the backend where we are allowing users to view private rooms.

The PR that is associated: https://github.com/turnbasedgames/server/pull/48

2022-09-10 01:55 UTC, kevo1ution requested changes

2022-09-10 01:55 UTC, kevo1ution commented on src/models/room.ts
>          getRooms({ gameId, finished: false, containsPlayer: userId }),
I think it makes sense to include `privateRooms: false` here too

2022-09-13 14:17 UTC, yquansah commented on src/models/room.ts
>          getRooms({ gameId, finished: false, containsPlayer: userId }),
@kevo1ution You think so? That means they can be in more than 1 room right? (A public and a private one)

2022-09-13 14:23 UTC, kevo1ution approved these changes

2022-09-13 14:23 UTC, merged